export const products = [ 
                  { 
//*************************************************CHAIRS*********************************
                  	"product"     : "chair 1", 
                    "price"       : 35, 
                    "quantity"    : 100, 
                    "category"    : "chairs", 
                    "categoryId"  : "9dhqTaMhycetEsnYm", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1526295494/oie_1412549bttFEn2a.jpg", 
                                                     "public_id" : "oie_1412549bttFEn2a" }]
                  },
                  { 
                  	"product"     : "chair 2", 
                    "price"       : 96, 
                    "quantity"    : 100, 
                    "category"    : "chairs", 
                    "categoryId"  : "9dhqTaMhycetEsnYm", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1526295494/oie_14125347W776WiHw.png", 
                                      "public_id" : "oie_14125347W776WiHw"}]
                  },
                  { 
                  	"product"     : "chair 3", 
                    "price"       : 76, 
                    "quantity"    : 100, 
                    "category"    : "chairs", 
                    "categoryId"  : "9dhqTaMhycetEsnYm", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1526295494/oie_1412528RBTsTX6h.png", 
                                      "public_id" : "oie_1412528RBTsTX6h"}]
                  },
                  { 
                  	"product"     : "chair 4", 
                    "price"       : 120, 
                    "quantity"    : 100, 
                    "category"    : "chairs", 
                    "categoryId"  : "9dhqTaMhycetEsnYm", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1526295494/oie_14125045LOHAdd94.jpg", 
                                      "public_id" : "oie_14125045LOHAdd94"}]
                  },
                  { 
                  	"product"     : "chair 5", 
                    "price"       : 147, 
                    "quantity"    : 100, 
                    "category"    : "chairs", 
                    "categoryId"  : "9dhqTaMhycetEsnYm", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1526295494/oie_14125236DvCYbWU5.jpg", 
                                      "public_id" : "oie_14125236DvCYbWU5" }]
                  },
                  { 
                  	"product"     : "chair 6", 
                    "price"       : 156, 
                    "quantity"    : 100, 
                    "category"    : "chairs", 
                    "categoryId"  : "9dhqTaMhycetEsnYm", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522677434/bsppuz2g3wazabgiazog.jpg", 
                                      "public_id" : "bsppuz2g3wazabgiazog"}]
                  },
                  { 
                  	"product"     : "chair 7", 
                    "price"       : 114, 
                    "quantity"    : 100, 
                    "category"    : "chairs", 
                    "categoryId"  : "9dhqTaMhycetEsnYm", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522676885/dzggity23iplp6tfwsoy.jpg", 
                                      "public_id" : "dzggity23iplp6tfwsoy"}]
                  },
                  { 
                  	"product"     : "chair 8", 
                    "price"       : 74, 
                    "quantity"    : 100, 
                    "category"    : "chairs", 
                    "categoryId"  : "9dhqTaMhycetEsnYm", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{  "url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522139221/mna7yadvvienati413v3.jpg", 
                                        "public_id" : "mna7yadvvienati413v3"}]
                  },
                  { 
                  	"product"     : "chair 9", 
                    "price"       : 125, 
                    "quantity"    : 100, 
                    "category"    : "chairs", 
                    "categoryId"  : "9dhqTaMhycetEsnYm", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522139155/zeiqfnbesmbplasxa2qj.png", 
                              "public_id" : "zeiqfnbesmbplasxa2qj"}]
                  },
                  { 
                  	"product"     : "chair 10", 
                    "price"       : 164, 
                    "quantity"    : 100, 
                    "category"    : "chairs", 
                    "categoryId"  : "9dhqTaMhycetEsnYm", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522676976/editlxtrnwnn0rs8yach.jpg", 
                              "public_id" : "editlxtrnwnn0rs8yach" }]
                  },
//******************************************************TABLES*********************************
                  { 
                  	"product"     : "table 1", 
                    "price"       : 98, 
                    "quantity"    : 100, 
                    "category"    : "tables", 
                    "categoryId"  : "wbJBSA9RPpeg7uTmH", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522694683/iwbcaqnbywriki2sdggi.jpg", 
                              "public_id" : "iwbcaqnbywriki2sdggi"}]
                  },
                  { 
                  	"product"     : "table 2", 
                    "price"       : 115, 
                    "quantity"    : 100, 
                    "category"    : "tables", 
                    "categoryId"  : "wbJBSA9RPpeg7uTmH", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522694690/ntdlcht8zzgrithcmdpn.jpg", 
                              "public_id" : "ntdlcht8zzgrithcmdpn"}]
                  },
                  { 
                  	"product"     : "table 3", 
                    "price"       : 128, 
                    "quantity"    : 100, 
                    "category"    : "tables", 
                    "categoryId"  : "wbJBSA9RPpeg7uTmH", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522694700/mvuaiivlkniah2wwybvc.jpg", 
                              "public_id" : "mvuaiivlkniah2wwybvc" }]
                  },
                  { 
                  	"product"     : "table 4", 
                    "price"       : 120, 
                    "quantity"    : 100, 
                    "category"    : "tables", 
                    "categoryId"  : "wbJBSA9RPpeg7uTmH", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{ "url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522694706/tic9ycgjwvfrc9oerhpy.jpg", 
                              "public_id" : "tic9ycgjwvfrc9oerhpy"}]
                  },
                  { 
                  	"product"     : "table 5", 
                    "price"       : 247, 
                    "quantity"    : 100, 
                    "category"    : "tables", 
                    "categoryId"  : "wbJBSA9RPpeg7uTmH", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522694713/iktjc8pv5d3rfypoueas.jpg", 
                              "public_id" : "iktjc8pv5d3rfypoueas"}]
                  },
                  { 
                  	"product"     : "table 6", 
                    "price"       : 256, 
                    "quantity"    : 100, 
                    "category"    : "tables", 
                    "categoryId"  : "wbJBSA9RPpeg7uTmH", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522694720/eorlmvpksvkw1ryb6kby.jpg", 
                              "public_id" : "eorlmvpksvkw1ryb6kby" }]
                  },
                  { 
                  	"product"     : "table 7", 
                    "price"       : 214, 
                    "quantity"    : 100, 
                    "category"    : "tables", 
                    "categoryId"  : "wbJBSA9RPpeg7uTmH", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{ "url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522694738/ces9qxlbf7frb1uncezv.jpg", 
                              "public_id" : "ces9qxlbf7frb1uncezv"}]
                  },
                  { 
                  	"product"     : "table 8", 
                    "price"       : 174, 
                    "quantity"    : 100, 
                    "category"    : "tables", 
                    "categoryId"  : "wbJBSA9RPpeg7uTmH", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522694746/zfgzgnovdspyajcotofh.jpg", 
                              "public_id" : "zfgzgnovdspyajcotofh"}]
                  },
                  { 
                  	"product"     : "table 9", 
                    "price"       : 125, 
                    "quantity"    : 100, 
                    "category"    : "tables", 
                    "categoryId"  : "wbJBSA9RPpeg7uTmH", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"product"   : "table 9",
                              "url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522694751/dfxmntu0vsy18lcpinip.jpg", 
                              "public_id" : "dfxmntu0vsy18lcpinip" }]
                  },
                  { 
                  	"product"     : "table 10", 
                    "price"       : 164, 
                    "quantity"    : 100, 
                    "category"    : "tables", 
                    "categoryId"  : "wbJBSA9RPpeg7uTmH", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522694758/vqm6h4ptlihhwbzzqcp5.jpg", 
                              "public_id" : "vqm6h4ptlihhwbzzqcp5" }]
                  },
//********************************************************SOFAS****************************
                  {
                    "product"     : "sofa 1", 
                    "price"       : 435, 
                    "quantity"    : 100, 
                    "category"    : "sofas", 
                    "categoryId"  : "7HYMmSdLTrdRp4nxQ", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522220503/ifrr1h0ocv821fn6ukaj.jpg", 
                              "public_id" : "ifrr1h0ocv821fn6ukaj"}]
                  },
                  { 
                  	"product"     : "sofa 2", 
                    "price"       : 596, 
                    "quantity"    : 100, 
                    "category"    : "sofas", 
                    "categoryId"  : "7HYMmSdLTrdRp4nxQ", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522220457/pwblilny5h77eisxhixa.jpg", 
                              "public_id" : "pwblilny5h77eisxhixa" }]
                  },
                  { 
                  	"product"     : "sofa 3", 
                    "price"       : 476, 
                    "quantity"    : 100, 
                    "category"    : "sofas", 
                    "categoryId"  : "7HYMmSdLTrdRp4nxQ", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{ "url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522689321/wnlm9axz7oekcyg76jtw.jpg", 
                              "public_id" : "wnlm9axz7oekcyg76jtw"}]
                  },
                  { 
                  	"product"     : "sofa 4", 
                    "price"       : 1120, 
                    "quantity"    : 100, 
                    "category"    : "sofas", 
                    "categoryId"  : "7HYMmSdLTrdRp4nxQ", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522690326/xgeftub5jpialvzuqnf5.jpg", 
                              "public_id" : "xgeftub5jpialvzuqnf5"}]
                  },
                  { 
                  	"product"     : "sofa 5", 
                    "price"       : 1147, 
                    "quantity"    : 100, 
                    "category"    : "sofas", 
                    "categoryId"  : "7HYMmSdLTrdRp4nxQ", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522690332/mupczi0tjbx15n8p2qwb.jpg", 
                              "public_id" : "mupczi0tjbx15n8p2qwb"}]
                  },
                  { 
                  	"product"     : "sofa 6", 
                    "price"       : 1156, 
                    "quantity"    : 100, 
                    "category"    : "sofas", 
                    "categoryId"  : "7HYMmSdLTrdRp4nxQ", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522690338/vjli4oefgx7jwaqsfddd.jpg", 
                              "public_id" : "vjli4oefgx7jwaqsfddd" }]
                  },
                  { 
                  	"product"     : "sofa 7", 
                    "price"       : 1140, 
                    "quantity"    : 100, 
                    "category"    : "sofas", 
                    "categoryId"  : "7HYMmSdLTrdRp4nxQ", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{  "url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522690343/a8gyhlvfmqnp24nptl7i.jpg", 
                              "public_id" : "a8gyhlvfmqnp24nptl7i" }]
                  },
                  { 
                  	"product"     : "sofa 8", 
                    "price"       : 740, 
                    "quantity"    : 100, 
                    "category"    : "sofas", 
                    "categoryId"  : "7HYMmSdLTrdRp4nxQ", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522690352/jbfkj7nshzpssyegeuve.jpg", 
                              "public_id" : "jbfkj7nshzpssyegeuve" }]
                  },
                  { 
                  	"product"     : "sofa 9", 
                    "price"       : 1250, 
                    "quantity"    : 100, 
                    "category"    : "sofas", 
                    "categoryId"  : "7HYMmSdLTrdRp4nxQ", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522690359/b61toz3pj8clbzoh8bss.jpg", 
                              "public_id" : "b61toz3pj8clbzoh8bss"}]
                  },
                  { 
                  	"product"     : "sofa 10", 
                    "price"       : 1645, 
                    "quantity"    : 100, 
                    "category"    : "sofas", 
                    "categoryId"  : "7HYMmSdLTrdRp4nxQ", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522690374/kaniqy0z9nx7jf3mix30.jpg", 
                              "public_id" : "kaniqy0z9nx7jf3mix30"}]
                  },
//********************************************************BEDS******************************
                  {
                    "product"     : "bed 1", 
                    "price"       : 435, 
                    "quantity"    : 100, 
                    "category"    : "beds", 
                    "categoryId"  : "bw94S9zxSLmmfhRYc", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{  "url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522695793/a2vhm69p4tkladuj5yj7.jpg", 
                              "public_id" : "a2vhm69p4tkladuj5yj7"}]
                  },
                  { 
                  	"product"     : "bed 2", 
                    "price"       : 350, 
                    "quantity"    : 100, 
                    "category"    : "beds", 
                    "categoryId"  : "bw94S9zxSLmmfhRYc", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522695800/pxlklr19fc9dxyspg5ou.jpg", 
                              "public_id" : "pxlklr19fc9dxyspg5ou" }]
                  },
                  { 
                  	"product"     : "bed 3", 
                    "price"       : 360, 
                    "quantity"    : 100, 
                    "category"    : "beds", 
                    "categoryId"  : "bw94S9zxSLmmfhRYc", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522695806/jp9ockvbny5r829uizuj.jpg", 
                              "public_id" : "jp9ockvbny5r829uizuj"}]
                  },
                  { 
                  	"product"     : "bed 4", 
                    "price"       : 520, 
                    "quantity"    : 100, 
                    "category"    : "beds", 
                    "categoryId"  : "bw94S9zxSLmmfhRYc", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522695812/o3dwahpjrvtbyegeec9l.jpg", 
                              "public_id" : "o3dwahpjrvtbyegeec9l"}]
                  },
                  { 
                  	"product"     : "bed 5", 
                    "price"       : 670, 
                    "quantity"    : 100, 
                    "category"    : "beds", 
                    "categoryId"  : "bw94S9zxSLmmfhRYc", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522695817/z8l208wwjkujou82ucll.jpg", 
                              "public_id" : "z8l208wwjkujou82ucll"}]
                  },
                  { 
                  	"product"     : "bed 6", 
                    "price"       : 350, 
                    "quantity"    : 100, 
                    "category"    : "beds", 
                    "categoryId"  : "bw94S9zxSLmmfhRYc", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522695824/jqmjlwd3lkz7c2qicwre.jpg", 
                              "public_id" : "jqmjlwd3lkz7c2qicwre" }]
                  },
                  { 
                  	"product"     : "bed 7", 
                    "price"       : 320, 
                    "quantity"    : 100, 
                    "category"    : "beds", 
                    "categoryId"  : "bw94S9zxSLmmfhRYc", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522695830/qqmsyv6ftxdgcxm3doag.jpg", 
                              "public_id" : "qqmsyv6ftxdgcxm3doag" }]
                  },
                  { 
                  	"product"     : "bed 8", 
                    "price"       : 367, 
                    "quantity"    : 100, 
                    "category"    : "beds", 
                    "categoryId"  : "bw94S9zxSLmmfhRYc", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522695840/tqdurewtzqtprnkm78k1.jpg", 
                              "public_id" : "tqdurewtzqtprnkm78k1" }]
                  },
                  { 
                  	"product"     : "bed 9", 
                    "price"       : 700, 
                    "quantity"    : 100, 
                    "category"    : "beds", 
                    "categoryId"  : "bw94S9zxSLmmfhRYc", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522696024/vyigbuz10xwomyrfgkgb.jpg", 
                              "public_id" : "vyigbuz10xwomyrfgkgb" }]
                  },
                  { 
                  	"product"     : "bed 10", 
                    "price"       : 800, 
                    "quantity"    : 100, 
                    "category"    : "beds", 
                    "categoryId"  : "bw94S9zxSLmmfhRYc", 
                    "description" : "Hay muchas variaciones de los pasajes de Lorem Ipsum disponibles, pero la mayoría sufrió alteraciones en alguna manera, ya sea porque se le agregó humor, o palabras aleatorias que no parecen ni un poco creíbles. ",
                    "details"     : "Measures 24.02 inches deep by 24.02 inches wide by 34.84 to 38.58 inches high; 1-year limited warranty",
                    "pictures"    : [{"url"       : "http://res.cloudinary.com/estefanodi2009/image/upload/v1522696029/znuxt8wenzcvjp6oh0hr.jpg", 
                              "public_id" : "znuxt8wenzcvjp6oh0hr"}]
                  }
               ]
